version: '2'
services:      
  db:
    image: mysql:5.7
    container_name: mydb_container
    volumes:
      - "./dbfiles:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: mydbname
      MYSQL_USER: myusername
      MYSQL_PASSWORD: myuserpassword
