version: '2'
services:
  theapp:
    build: .
    image: somombo/php-test
    container_name: php-test
    volumes:
      - "./src:/var/www/html"
      - "./config/php.ini:/usr/local/etc/php/php.ini"
    ports:
      - "80:80"
    restart: always     
    depends_on:
      - db
    links:
      - db

  pma:
    extends:
      file: ../phpMyAdmin/docker-compose.yml
      service: phpmyadmin
    links:
      - db
    depends_on:
      - db
      
  db:
    extends:
      file: ../storage/docker-compose.yml
      service: db



